In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel('dataset.xlsx')

In [3]:
df

sepal length  sepal width  petal length  petal width       iris type
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()

In [5]:
values=encoder.fit_transform(df[['iris type']])

In [6]:
values

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [7]:
df['iris type'] = values

In [8]:
df

sepal length  sepal width  petal length  petal width  iris type
0             5.1          3.5           1.4          0.2        0.0
1             4.9          3.0           1.4          0.2        0.0
2             4.7          3.2           1.3          0.2        0.0
3             4.6          3.1           1.5          0.2        0.0
4             5.0          3.6           1.4          0.2        0.0
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3        2.0
146           6.3          2.5           5.0          1.9        2.0
147           6.5          3.0           5.2          2.0        2.0
148           6.2          3.4           5.4          2.3        2.0
149           5.9          3.0           5.1          1.8        2.0

[150 rows x 5 columns]

In [9]:
train_df = df[['sepal length','sepal width','petal length','petal width']]
train_df

sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(train_df,df['iris type'],test_size = 0.33)

In [11]:
y_train

17     0.0
87     1.0
31     0.0
24     0.0
138    2.0
      ... 
23     0.0
65     1.0
126    2.0
12     0.0
108    2.0
Name: iris type, Length: 100, dtype: float64

In [12]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier()

In [13]:
model.predict(np.array([1,2,3,1]).reshape(1,-1))

array([1.])

In [14]:
x_test

sepal length  sepal width  petal length  petal width
149           5.9          3.0           5.1          1.8
122           7.7          2.8           6.7          2.0
36            5.5          3.5           1.3          0.2
38            4.4          3.0           1.3          0.2
129           7.2          3.0           5.8          1.6
115           6.4          3.2           5.3          2.3
1             4.9          3.0           1.4          0.2
68            6.2          2.2           4.5          1.5
90            5.5          2.6           4.4          1.2
93            5.0          2.3           3.3          1.0
26            5.0          3.4           1.6          0.4
140           6.7          3.1           5.6          2.4
123           6.3          2.7           4.9          1.8
18            5.7          3.8           1.7          0.3
61            5.9          3.0           4.2          1.5
104           6.5          3.0           5.8          2.2
48            5.3          3.7           1.5          0.2
147           6.5          3.0           5.2          2.0
116           6.5          3.0           5.5          1.8
133           6.3          2.8           5.1          1.5
30            4.8          3.1           1.6          0.2
0             5.1          3.5           1.4          0.2
127           6.1          3.0           4.9          1.8
7             5.0          3.4           1.5          0.2
64            5.6          2.9           3.6          1.3
145           6.7          3.0           5.2          2.3
84            5.4          3.0           4.5          1.5
128           6.4          2.8           5.6          2.1
51            6.4          3.2           4.5          1.5
146           6.3          2.5           5.0          1.9
105           7.6          3.0           6.6          2.1
137           6.4          3.1           5.5          1.8
54            6.5          2.8           4.6          1.5
72            6.3          2.5           4.9          1.5
45            4.8          3.0           1.4          0.3
148           6.2          3.4           5.4          2.3
96            5.7          2.9           4.2          1.3
50            7.0          3.2           4.7          1.4
85            6.0          3.4           4.5          1.6
82            5.8          2.7           3.9          1.2
62            6.0          2.2           4.0          1.0
75            6.6          3.0           4.4          1.4
80            5.5          2.4           3.8          1.1
110           6.5          3.2           5.1          2.0
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
103           6.3          2.9           5.6          1.8
101           5.8          2.7           5.1          1.9
86            6.7          3.1           4.7          1.5
74            6.4          2.9           4.3          1.3

In [15]:
from sklearn.metrics import f1_score
y_predict = model.predict(x_test)
score = f1_score(y_test,y_predict,average = 'micro')

In [16]:
score

0.96

In [17]:
from sklearn.tree import DecisionTreeClassifier
treemodel = DecisionTreeClassifier()
treemodel.fit(x_train,y_train)

DecisionTreeClassifier()

In [18]:
y_predict_tree = model.predict(x_test)
score_tree = f1_score(y_test,y_predict_tree,average='micro')

In [19]:
score_tree

0.96

In [20]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
x_train_std = scalar.fit_transform(x_train)
x_train_std

array([[-0.75745124,  0.90731023, -1.19619529, -1.04574164],
       [ 0.62813029, -1.72257449,  0.45070048,  0.22490434],
       [-0.41105585,  0.68815317, -1.14129877, -0.91867704],
       [-1.10384662,  0.68815317, -0.92171267, -1.17280624],
       [ 0.28173491, -0.18847507,  0.67028658,  0.86022733],
       [ 1.55185131, -0.18847507,  1.27414836,  1.24142112],
       [-0.87291636,  0.24983905, -1.30598835, -1.17280624],
       [-0.64198611,  0.68815317, -1.19619529, -1.17280624],
       [ 1.0899908 ,  0.46899611,  1.16435531,  1.74967951],
       [-0.87291636, -0.18847507, -1.08640224, -1.17280624],
       [ 0.05080466, -0.84594625,  0.83497616,  0.98729193],
       [-0.87291636,  1.12646729, -1.19619529, -1.17280624],
       [-0.75745124,  0.68815317, -1.14129877, -1.17280624],
       [ 0.62813029,  0.68815317,  1.10945878,  1.62261492],
       [-0.98838149, -1.28426037,  0.505597  ,  0.73316273],
       [ 0.39720004, -1.06510331,  1.10945878,  0.35196894],
       [-0.87291636,  0.

In [21]:
treemodel.fit(x_train_std,y_train)

DecisionTreeClassifier()

In [22]:
x_test_std = scalar.fit_transform(x_test)
y_predict_std = treemodel.predict(x_test_std)
score_std = f1_score(y_test,y_predict_std,average='micro')

In [23]:
score_std

0.8000000000000002

In [24]:
#so the most accurate model is the decision tree one without using a standard scalar

In [25]:
from sklearn.svm import SVC
svc_model = SVC()
svc_model.fit(x_train,y_train)
ypredict_svc = svc_model.predict(x_test)
score_svc = f1_score(y_test,y_predict,average='micro')
score_svc

0.96

In [26]:
svc_model.fit(x_train_std,y_train)
y_predict_svc_std = svc_model.predict(x_test_std)
score_svc_std = f1_score(y_test,y_predict_svc_std,average = 'micro')
score_svc_std

0.82

In [27]:
treemodel.fit(x_train,y_train)
predict_train = treemodel.predict(x_train)
train_score = f1_score(y_train,predict_train,average='micro')
train_score

1.0

In [29]:
#now let's do it with a RFC tuned with gridsearch
from sklearn.model_selection import GridSearchCV
RFC = RandomForestClassifier(random_state=42)
param_grid = { 
    'n_estimators': [20, 100],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : [2,3,4,5,6,7],
    'criterion' :['gini', 'entropy']
}
tunedRFC = GridSearchCV(RFC,param_grid=param_grid,cv=5)
tunedRFC.fit(x_train,y_train)


GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 3, 4, 5, 6, 7],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [20, 100]})

In [30]:
tunedRFC.best_params_

{'criterion': 'gini',
 'max_depth': 4,
 'max_features': 'auto',
 'n_estimators': 100}

In [31]:
finalRFC = RandomForestClassifier(criterion='gini',max_depth=4,max_features='auto',n_estimators=100)
finalRFC.fit(x_train,y_train)
y_predict_tuned = finalRFC.predict(x_test)
score_tuned = f1_score(y_test,y_predict_tuned,average='micro')
score_tuned

0.98

In [ ]:
#finally we have reached highest accuracy on test model 0.98 remember the score is calculated using f1_score which is
#usually used with classification problems however there are other techniques to be discussed later.
